version: '3'
services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: slava
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: database
    networks:
      - backend

networks:
  backend:
    driver: bridge
